import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import Script from 'next/script'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: 'swap',
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <head />
      <body suppressHydrationWarning>
        <Script 
          src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
          strategy="afterInteractive"
        />
        <Script 
          src="https://api.windy.com/assets/map-forecast/libBoot.js?use=leaflet"
          strategy="afterInteractive"
        />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
